const String syarantKetentuanEdupass = '''
Selamat datang di Aplikasi Mobile PT Kunci Transformasi Digital, yang dapat diakses di http://edupass.id/. Dengan menggunakan Aplikasi Mobile ini, Anda setuju untuk mematuhi syarat dan ketentuan berikut ini. Jika Anda tidak setuju, mohon untuk menghentikan penggunaan Edupass.

Dengan mengakses dan menggunakan layanan kami, Anda secara otomatis menyetujui untuk terikat oleh syarat dan ketentuan berikut ini. Kami berhak untuk mengubah syarat dan ketentuan ini sesuai kebijakan kami tanpa pemberitahuan sebelumnya. Anda bertanggung jawab untuk mematuhi semua hukum dan peraturan yang berlaku dalam menggunakan layanan kami. Informasi pribadi yang Anda berikan akan diurus sesuai dengan kebijakan privasi kami. Anda setuju untuk tidak menggunakan layanan kami untuk tujuan yang melanggar hukum atau melanggar hak orang lain. Semua transaksi pembayaran harus dilakukan sesuai dengan ketentuan yang disepakati. Kami tidak bertanggung jawab atas kerugian atau kerusakan yang timbul dari penggunaan atau ketidakmampuan menggunakan layanan kami. Syarat dan ketentuan ini diatur oleh hukum di Indonesia, dan segala sengketa akan diselesaikan di pengadilan yang berwenang dari yurisdiksi tersebut. Kami berhak untuk mengubah syarat dan ketentuan ini tanpa pemberitahuan sebelumnya, dan pengguna disarankan untuk memeriksa halaman ini secara berkala untuk pembaruan. Untuk informasi lebih lanjut atau pertanyaan mengenai syarat dan ketentuan ini, silakan hubungi kami melalui email/kontak yang tersedia.

Dalam perjanjian ini, istilah "Kami" dan "Perusahaan" digunakan untuk mengidentifikasi PT Kunci Transformasi Digital sebagai penyedia layanan yang mengelola Aplikasi Mobile ini. Di sisi lain,  istilah "Anda" dan "Klien" merujuk kepada individu yang mengakses Aplikasi ini dan menyetujui syarat yang ditetapkan. Syarat dan ketentuan yang kami tetapkan dalam perjanjian ini bertujuan untuk mengatur kewajiban timbal balik, penerimaan, dan pertimbangan yang diperlukan untuk memberikan layanan secara efektif guna memenuhi kebutuhan Klien kami.

Hal ini memastikan bahwa setiap klausul dan persyaratan yang diuraikan dalam perjanjian ini diterapkan secara konsisten terhadap semua pihak yang terlibat, baik Klien maupun PT Kunci Transformasi Digital. Variasi dalam terminologi yang digunakan dalam perjanjian ini—baik itu dalam bentuk kapitalisasi, tunggal,  kata ganti, atau  jamak mengacu pada entitas atau konsep yang sama. Kami menghargai transparansi dan kejelasan dalam memastikan bahwa persyaratan yang diberlakukan dapat dipahami dengan baik oleh semua pihak yang terlibat dalam penggunaan layanan kami.

Istilah "Pihak" secara kolektif mencakup baik Klien maupun Perusahaan, mencakup segala aspek yang relevan termasuk Syarat dan Ketentuan, Pernyataan Privasi, dan Pemberitahuan Penolakan. Perjanjian ini dirancang untuk memastikan bahwa hak dan kewajiban kedua belah pihak diatur secara jelas dan transparan, mencerminkan komitmen kami terhadap pengalaman pengguna yang positif dan kepatuhan terhadap peraturan yang berlaku. Kami menghargai keterlibatan Anda dalam menggunakan layanan kami dan siap memberikan klarifikasi lebih lanjut jika diperlukan mengenai ketentuan yang telah kami tetapkan.
''';

const String ketentuanPembayaranEdupass = '''
Akses ke Layanan atau fitur khusus di Edupass mungkin memerlukan pembayaran biaya tertentu. Sebelum Anda melanjutkan dengan pembayaran, Anda akan diberi kesempatan untuk meninjau dan menerima biaya yang diperlukan. Semua biaya yang terkait dengan layanan atau fitur tersebut akan jelas dijelaskan dalam mata uang Rupiah Indonesia (IDR) dan tidak dapat dikembalikan setelah proses pembayaran selesai.

Kami memahami pentingnya transparansi dalam urusan keuangan, oleh karena itu kami menekankan bahwa semua biaya yang Anda setujui akan dipaparkan secara rinci sebelum Anda mengonfirmasi transaksi. Ini bertujuan untuk memastikan bahwa Anda sepenuhnya mengerti dan menerima jumlah biaya yang harus Anda bayar untuk menggunakan layanan atau fitur tertentu di Edupass. Kami menyarankan Anda untuk memeriksa dengan cermat informasi biaya yang tertera sebelum melanjutkan, sehingga Anda dapat membuat keputusan yang tepat sesuai dengan kebutuhan dan anggaran Anda.

Kami berkomitmen untuk menjaga integritas sistem pembayaran kami dengan menawarkan kejelasan dan kesempatan bagi Anda untuk menilai dan menyetujui biaya yang terkait sebelum Anda melakukan pembayaran. Jika Anda memiliki pertanyaan lebih lanjut tentang biaya atau ingin memahami lebih lanjut tentang prosedur pembayaran di Edupass, jangan ragu untuk menghubungi tim dukungan kami melalui saluran komunikasi yang tersedia di Aplikasi Mobile kami.

''';

const String cookiesEdupass = '''
Aplikasi Mobile kami, Edupass, menggunakan cookies untuk meningkatkan pengalaman pengguna. Cookies adalah file teks kecil yang disimpan pada perangkat Anda ketika Anda mengunjungi Aplikasi Mobile kami. Mereka umumnya digunakan oleh Aplikasi Mobile interaktif untuk mengingat detail pengguna, seperti preferensi dan riwayat kunjungan, untuk kunjungan berikutnya. Di Edupass, cookies membantu kami memfasilitasi beberapa fungsionalitas, seperti menyimpan preferensi bahasa atau pengaturan lainnya, sehingga Anda dapat mengakses konten dengan lebih mudah dan efisien.

Selain meningkatkan fungsionalitas Aplikasi Mobile, cookies juga membantu kami memahami bagaimana pengguna berinteraksi dengan Edupass. Ini termasuk analisis penggunaan Aplikasi dan pengumpulan data demografis secara anonim untuk tujuan statistik. Beberapa mitra afiliasi dan pengiklan kami juga dapat menggunakan cookies untuk mengumpulkan informasi tentang aktivitas Anda di Aplikasi kami, seperti untuk menampilkan iklan yang sesuai dengan minat Anda di masa mendatang.

Dengan menggunakan Edupass, Anda secara otomatis menyetujui penggunaan cookies kami sebagaimana dijelaskan dalam Kebijakan Privasi PT Kunci Transformasi Digital. Anda memiliki opsi untuk mengontrol atau menghapus cookies melalui pengaturan browser Anda. Namun, perlu dicatat bahwa memblokir cookies dapat mempengaruhi pengalaman pengguna Anda dan dapat menyebabkan beberapa fitur Aplikasi tidak berfungsi dengan baik. Untuk informasi lebih lanjut tentang bagaimana kami menggunakan cookies dan bagaimana Anda dapat mengelola preferensi cookie Anda, silakan lihat Kebijakan Privasi kami atau hubungi kami melalui informasi kontak yang tersedia di Aplikasi Mobile ini.
''';

const String kebijakanPrivasiEdupass = '''
Kebijakan Privasi kami menjelaskan secara rinci informasi yang dikumpulkan oleh Edupass ketika Anda dan pengguna lain menggunakan Aplikasi Mobile ini. Informasi yang kami kumpulkan meliputi data pribadi seperti nama, alamat email, informasi kontak lainnya, dan informasi yang relevan untuk penggunaan layanan kami. Kami menggunakan informasi pribadi ini untuk menyediakan layanan, memperbaiki pengalaman pengguna, mengelola akun Anda, dan untuk tujuan lain yang diperlukan sesuai dengan kebijakan privasi kami.

Kami berkomitmen untuk melindungi privasi dan keamanan informasi pribadi Anda. Kami tidak akan menjual, menyewakan, atau mentransfer informasi pribadi Anda kepada pihak ketiga tanpa izin Anda, kecuali seperti yang diatur dalam Kebijakan Privasi atau seperti yang diizinkan atau diwajibkan oleh hukum. Kami dapat mengungkapkan informasi pribadi Anda kepada penyedia layanan yang membantu kami dalam menyediakan layanan, atau kepada pihak ketiga jika diperlukan untuk mematuhi hukum atau menjaga keamanan Aplikasi Mobile kami.

Dengan menyetujui Syarat Layanan kami, Anda juga secara eksplisit memberikan persetujuan untuk pengumpulan, penggunaan, dan pengungkapan informasi pribadi Anda sesuai dengan Kebijakan Privasi kami. Kami mendorong Anda untuk membaca Kebijakan Privasi kami dengan seksama untuk memahami bagaimana kami mengumpulkan, menggunakan, dan melindungi informasi pribadi Anda. Jika Anda memiliki pertanyaan atau memerlukan klarifikasi lebih lanjut mengenai Kebijakan Privasi kami, jangan ragu untuk menghubungi kami melalui informasi kontak yang tersedia di Aplikasi Mobile ini.

''';

const String lisensiEdupass = '''
Seluruh hak kekayaan intelektual untuk materi di Edupass dimiliki oleh PT Kunci Transformasi Digital dan/atau para lisensinya, kecuali dinyatakan lain, dan hak-hak ini dilindungi. Pengguna diizinkan untuk menggunakan Edupass hanya untuk tujuan pribadi. PT Kunci Transformasi Digital memiliki otoritas untuk memantau semua Konten dan menghapus Konten yang dianggap tidak pantas, menghina, atau melanggar Syarat dan Ketentuan ini.

Beberapa bagian dari Aplikasi Mobile ini memfasilitasi pengguna untuk memposting dan bertukar pendapat serta informasi. PT Kunci Transformasi Digital tidak melakukan pra-penyaringan, pengeditan, penerbitan, atau tinjauan terhadap Konten sebelum Konten tersebut muncul di Aplikasi Mobile. Konten yang diposting mencerminkan pandangan dan pendapat individu yang mengirimnya, bukan pandangan dari PT Kunci Transformasi Digital, agen, atau afiliasinya.

Sejauh yang diizinkan oleh hukum, PT Kunci Transformasi Digital tidak bertanggung jawab atas Konten atau atas tanggung jawab, kerusakan, atau biaya yang mungkin timbul dari penggunaan, penempatan, atau penampilan Konten di Aplikasi Mobile ini. Ini mencakup segala konsekuensi dari keputusan yang diambil berdasarkan Konten tersebut oleh pengguna Aplikasi Mobile.

Dengan menggunakan layanan kami atau mengirimkan Konten ke Aplikasi Mobile Edupass, Anda memberikan PT Kunci Transformasi Digital lisensi non-eksklusif untuk menggunakan, mereproduksi, mengedit, dan mengizinkan orang lain untuk menggunakan, mereproduksi, dan mengedit Konten Anda. Lisensi ini mencakup hak untuk menggunakan Konten Anda dalam berbagai bentuk, format, atau media yang ada atau yang akan dikembangkan di masa depan. Tujuan dari lisensi ini adalah untuk memungkinkan kami mengelola, mempromosikan, dan meningkatkan layanan kami, serta untuk memastikan bahwa Konten yang Anda berikan dapat diakses dan digunakan secara efektif oleh pengguna kami.

Dalam memberikan lisensi ini, Anda tetap memegang hak kepemilikan intelektual atas Konten yang Anda buat dan mengirimkan. Namun, Anda memahami dan menyetujui bahwa dengan memberikan lisensi ini kepada kami, Anda memberikan izin kepada PT Kunci Transformasi Digital untuk menggunakan Konten Anda sesuai dengan syarat dan ketentuan yang dijelaskan dalam perjanjian ini. Anda juga menegaskan bahwa Konten yang Anda berikan tidak melanggar hak-hak kekayaan intelektual pihak ketiga, seperti hak cipta, paten, atau merek dagang.

Anda dilarang untuk mempublikasikan kembali, mereproduksi, menggandakan, menyalin, menjual, menyewakan, men-sublisensikan, atau mendistribusikan materi apa pun dari Edupass tanpa izin sebelumnya yang diberikan secara tertulis oleh PT Kunci Transformasi Digital. Larangan ini dimaksudkan untuk melindungi hak kekayaan intelektual Edupass, termasuk tetapi tidak terbatas pada konten, desain grafis, dan elemen lain yang terdapat dalam Aplikasi Mobile ini. Kami menerapkan langkah-langkah ini untuk memastikan bahwa penggunaan materi dari Edupass sesuai dengan syarat dan ketentuan yang telah ditetapkan.

Langkah-langkah perlindungan ini bertujuan untuk memastikan bahwa hak kekayaan intelektual Edupass terjaga dengan baik dan bahwa semua pengguna Aplikasi Mobile ini mematuhi peraturan yang berlaku. Dengan demikian, Anda diharapkan untuk tidak menyalahgunakan atau melanggar ketentuan ini dalam bentuk apa pun. Perjanjian ini berlaku sejak tanggal Anda mengakses Aplikasi Mobile Edupass dan terus berlaku selama Anda menggunakan layanan yang disediakan oleh PT Kunci Transformasi Digital.
''';

const String informasiKontakEdupass = '''
Jika Anda memiliki pertanyaan lebih lanjut atau memerlukan bantuan tambahan, silakan hubungi kami melalui formulir kontak online yang tersedia di Aplikasi Mobile kami. Tim dukungan kami siap membantu dan merespons pertanyaan Anda secepat mungkin. Kami memprioritaskan pengalaman pengguna yang baik dan berkomitmen untuk menyediakan layanan pelanggan yang memuaskan.

Untuk keperluan pengiriman pemberitahuan hukum atau layanan proses, harap gunakan alamat yang telah kami sediakan di bawah ini. Kami akan menanggapi pemberitahuan hukum yang diterima sesuai dengan prosedur yang ditetapkan dan sesuai dengan hukum yang berlaku. Pastikan untuk menyertakan informasi yang relevan dan kontak yang valid agar kami dapat merespons dengan tepat dan tepat waktu.

Pusat Bantuan kami menyediakan informasi terperinci tentang layanan kami, termasuk panduan, FAQ, dan instruksi yang dapat membantu Anda memahami lebih baik tentang fitur dan kebijakan yang berlaku di Edupass. Jika Anda memerlukan bantuan teknis atau memiliki pertanyaan tentang penggunaan platform kami, kunjungi Pusat Bantuan atau hubungi tim dukungan kami untuk mendapatkan bantuan langsung.
''';

const String penolakanEdupass = '''
Sejauh yang diizinkan oleh hukum yang berlaku, kami menolak semua representasi, jaminan, dan kondisi tentang Aplikasi Mobile kami dan penggunaannya. Kami tidak memberikan jaminan bahwa Aplikasi Mobile ini bebas dari kesalahan, bahwa layanannya akan selalu tersedia secara tanpa gangguan, atau bahwa informasi yang disediakan akan selalu akurat, lengkap, atau terkini. Penggunaan Aplikasi Mobile ini sepenuhnya atas risiko Anda sendiri, dan Anda bertanggung jawab untuk menilai keakuratan, kelengkapan, dan kelayakan informasi yang tersedia sebelum mengambil tindakan atau keputusan berdasarkan informasi tersebut.

Namun demikian, penolakan ini tidak membatasi atau mengecualikan tanggung jawab kami atau Anda atas kematian atau cedera pribadi, penipuan, representasi palsu, atau tanggung jawab lain yang tidak dapat dikecualikan berdasarkan hukum yang berlaku. Ini termasuk tetapi tidak terbatas pada tanggung jawab kami untuk mematuhi kewajiban hukum yang ada atau untuk menghindari pelanggaran hak-hak yang dilindungi oleh hukum. Harap diperhatikan bahwa pengecualian ini berlaku secara hukum dan mengatur semua tanggung jawab yang mungkin timbul di bawah penolakan ini, termasuk tanggung jawab dalam kontrak, hukum tort, atau kewajiban statutory.

Meskipun Aplikasi Mobile kami, serta informasi dan layanan yang tersedia di dalamnya, disediakan secara gratis, kami tidak akan bertanggung jawab atas kehilangan atau kerusakan dari segala jenis. Ini mencakup, namun tidak terbatas pada, kerugian langsung, tidak langsung, insidental, konsekuensial, atau punitive yang mungkin timbul dari penggunaan atau ketidakmampuan untuk menggunakan Aplikasi Mobile atau kontennya. Meskipun kami berusaha menyediakan informasi yang akurat dan layanan yang handal, kami tidak dapat menjamin bahwa Aplikasi Mobile ini bebas dari kesalahan atau bahwa layanannya akan selalu tersedia tanpa gangguan.

Penting bagi pengguna untuk memahami dan mengakui batasan ini sebelum mengakses atau menggunakan Aplikasi Mobile kami. Kami menyarankan untuk menggunakan informasi yang tersedia di Aplikasi Mobile ini dengan bijak dan dengan mempertimbangkan resiko yang terkait. Kami tidak bertanggung jawab atas kerugian atau kerusakan apa pun yang mungkin timbul akibat penggunaan atau ketergantungan pada informasi yang diperoleh dari Aplikasi Mobile ini. Dalam hal terjadi masalah atau ketidaknyamanan terkait layanan kami, kami berkomitmen untuk memperbaiki situasi tersebut sesuai dengan kemampuan dan kebijakan yang berlaku.

Kami menghargai partisipasi Anda dalam menggunakan layanan kami dan selalu siap memberikan klarifikasi atau informasi tambahan mengenai kebijakan dan batasan yang telah kami tetapkan. Untuk pertanyaan lebih lanjut atau jika Anda membutuhkan bantuan, jangan ragu untuk menghubungi tim dukungan kami yang siap membantu dengan informasi yang lebih detail.

Penolakan tanggung jawab ini berlaku sejauh yang diizinkan oleh hukum dan mencakup semua tanggung jawab yang timbul dalam kontrak, tort, dan pelanggaran kewajiban statutory. Artinya, kami tidak akan bertanggung jawab atas kehilangan atau kerusakan apa pun, termasuk kerugian langsung, tidak langsung, insidental, konsekuensial, atau punitive yang mungkin timbul dari penggunaan atau ketidakmampuan menggunakan Aplikasi Mobile atau kontennya, bahkan jika kami telah diberitahu tentang kemungkinan kerusakan tersebut.

Pengguna Aplikasi Mobile kami diharapkan untuk memahami dan mengakui batasan ini sebelum mengakses atau menggunakan layanan kami. Dengan menggunakan Aplikasi Mobile ini, pengguna menyetujui bahwa pembatasan dan pengecualian tanggung jawab ini merupakan bagian yang tidak terpisahkan dari syarat penggunaan kami, serta mengakui bahwa penggunaan Aplikasi Mobile ini sepenuhnya berada di bawah risiko mereka sendiri.
''';
